apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: YCAJEMoMSGb          #Отобразил не весь KeyID
  secretAccessKey: YCPI_lI4U        #Отобразил не весь AccessKey
  endpoint: https://storage.yandexcloud.net
