all:
  hosts:
    k8smaster01:
      ansible_host: 192.168.1.120
      ip: 192.168.1.120
      access_ip: 192.168.1.120
    k8smaster02:
      ansible_host: 192.168.1.121
      ip: 192.168.1.121
      access_ip: 192.168.1.121
    k8smaster03:
      ansible_host: 192.168.1.122
      ip: 192.168.1.122
      access_ip: 192.168.1.122
    k8sworker01:
      ansible_host: 192.168.1.123
      ip: 192.168.1.123
      access_ip: 192.168.1.123
    k8sworker02:
      ansible_host: 192.168.1.124
      ip: 192.168.1.124
      access_ip: 192.168.1.124
    k8sworker03:
      ansible_host: 192.168.1.125
      ip: 192.168.1.125
      access_ip: 192.168.1.125
    k8sworker04:
      ansible_host: 192.168.1.126
      ip: 192.168.1.126
      access_ip: 192.168.1.126
    k8sworker05:
      ansible_host: 192.168.1.127
      ip: 192.168.1.127
      access_ip: 192.168.1.127
  children:
    kube_control_plane:
      hosts:
        k8smaster01:
        k8smaster02:
        k8smaster03:
    kube_node:
      hosts:
        k8sworker01:
        k8sworker02:
        k8sworker03:
        k8sworker04:
        k8sworker05:
    etcd:
      hosts:
        k8smaster01:
        k8smaster02:
        k8smaster03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}