apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-templating
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-10OTUS/sultan_usmanov_repo.git
    path: kubernetes-templating/kubernetes-templating
    targetRevision: HEAD
    helm:
      parameters:
        - name: replicaCount
          value: '2'
      kubeVersion: 1.31.1
  destination:
    server: https://kubernetes.default.svc
    namespace: homeworkhelm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true