apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: kube-mon-svc
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 10s