apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-templating.fullname" . }}-configmap
  namespace: homework
data:
  default.conf: |
    server {
       listen *:8000 default_server;
       server_name  localhost;

       location / {
            root "/homework";
            autoindex on;
        }
    }
