apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-volume-pvc
  namespace: homework
spec:
  storageClassName: kube-volume-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi