apiVersion: v1
kind: Pod
metadata:
  name: kube-intro-app
  labels:
    app.kubernetes.io/name: kube-intro-app
  namespace: homework
spec:
  containers:
  - name: kube-intro-app
    image: nginx:1.29.3
    lifecycle:
      preStop:
        exec:
          command: ["rm", "/homework/index.html"]
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: "/homework"
    - name: nginx-config-volume
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
  initContainers:
  - name: init-container
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - https://ya.ru
    volumeMounts:
    - name: workdir
      mountPath: "/init"
  volumes:
  - name: workdir
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
      name: nginx-conf-configmap